version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx_container
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
