# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to S3

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['development']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
    uses: actions/checkout@v4

    - name: Install AWS CLI
    run: |
      sudo apt-get update
      sudo apt-get install -y python3-pip
      pip3 install awscli --update --user

    - name: Set up node
    uses: actions/setup-node@4
    with:
      node-version: 20
      cache: 'npm'
    
    - name: Install dependencies
    run: npm ci
    
    - name: Build site
    run: npm run build

    - name: Deploy to S3
    run: |
      aws s3 sync dist/ s3://${{ secrets.BUCKET_NAME }} --delete

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
